version: "3"

services:
  backend:
    container_name: backend
    build: 
      context: ./Backend-test
    image: devops_backend
    ports:
      - "8081:8081"
  fontend:
    container_name: fontend
    build:
      context: ./Fontend-master1
    image: devops_fontend
    ports:
      - "80:80"
    depends_on: 
      - backend
    network_mode: "host"


networks:
  default:
    external:
      name: project-network
  